USE Team13;
GO

-- Arizona Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Mason Bray', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Adam Damante', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brayden Dorman', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Noah Fifita', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Anthony Garcia', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cole Tannenbaum', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Quali Conley', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Jacory Croskey-Merritt', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Brandon Johnson', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kayden Luke', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Rayshon Luke', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Kedrick Reescano', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Anthony Wilhite', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jaden Clark', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Sam Graci-Glazer', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Rex Haynes', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jackson Holman', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Chris Hunter', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Devin Hyatt', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'AJ Jones', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Montana Lemonious-Craig', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Jordan McCord III', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tetairoa McMillan', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Reymello Murphy', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Julius Oliver', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jeremiah Patterson', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Brandon Phelps', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Malachi Riley', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Keyan Burnett', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'John Hart', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Roberto Miranda', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Sam Olson', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Tyler Powell', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dylan Tapley', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dorian Thomas', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Josh Baker', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Joey Capra', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Alexander Doost', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tylen Gonzalez', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'JT Hand', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Matthew Lado', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Leif Magnuson', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Shancco Matautia', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Wendell Moe Jr.', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Elijha Payne', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Raymond Pulido', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jonah Rodriguez', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jonah Savaiinaea', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Ryan Stewart', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Grayson Stovall', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Rhino Tapa''atoutai', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Zarius Wells', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael Wooten', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Arizona Defense', 15, N' ', N'Healthy', N'Active'),
 (N'Tyler Loop', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Michael Salgado-Medina', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Lachlan Bruce', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Jordan Forbes', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cash Peterman', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Justin Holloway', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Trey Naughton', 15, N'Sophomore' , N'Healthy' , N'Active');
GO

-- Arizona State Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Trenton Bourguet', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Navi Bruzon', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Christian Hunt', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Laskaris', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sam Leavitt', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jeff Sims', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'DeCarlos Brooks', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Kyson Brown', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Raleek Brown', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jason Brown Jr.', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Alton McCaskill', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Cam Skattebo', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Kaleb Black', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Coben Bourguet', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Armon Collins', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Deric English', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Derek Eusebio', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Xavier Guillory', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Korbin Hendrix', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Malik McClain', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Troy Omeire', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Zechariah Sample', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jake Smith', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Justice Spann', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Melquan Stovall', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Jordyn Tyson', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Max Ware', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jamaal Young II', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Coleson Arends', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Markeston Douglas', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Jayden Fortier', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'James Giggey', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cameron Harpole', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Chamon Metayer', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Sinjin Schmitt', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Josh Atkins', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Emmit Bohle', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Cade Briggs', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Connor Cameron', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ben Coleman', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Luis Cordova', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Leif Fautanu', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Colby Garvin', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Kaden Haeckel', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Max Iheanachor', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Sirri Kandiyeli', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Keim', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Terrell Kim', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jalen Klemm', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brandon Lloyd', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Sean Na''a', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Keona Peat', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Makua Pule', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kyle Scott', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Joey Su''a', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Semisi Tonga', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Bram Walden', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Champ Westbrooks', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Arizona State Defense', 14, N' ', N'Healthy', N'Active'),
 (N'Ian Hershey', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Carston Kieffer', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Parker Lewis', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Kanyon Floyd', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Race Mahlum', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Cole Marszalek', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Wigglesworth', 14, N'Sophomore' , N'Healthy' , N'Active');
GO

-- Baylor Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Nate Bennett', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dequan Finn', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Brayson McHenry', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Sawyer Robertson', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Cade Tessier', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joseph Dodds', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joseph Hagman', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dawson Pendergrass', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Richard Reese', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Dominic Richardson', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Bryson Washington', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Baird', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Monaray Baldwin', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Jamaal Bell', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Cameron Bonner', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Jonah Burton', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Josh Cameron', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Isaiah Davis', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Daniel Edeni', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Micah Gifford', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ashtyn Hawkins', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Ketron Jackson Jr.', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Jadon Porter', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hal Presley', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Seth Weller', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Kelsey Johnson', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Matthew Klopfenstein', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cody Mladenka', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Hawkins Polley', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael Trigg', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Gavin Yates', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Omar Aigbedion', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Campbell Barrington', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Gavin Byers', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Alvin Ebosele', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Sidney Fugar', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Ka''Marii Landers', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Ryan Lengyel', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Coleton Price', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Isaiah Robinson', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kaden Sieracki', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Koltin Sieracki', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Wyatt Swaner', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Colton Thomasson', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Sean Thompkins', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cayden Tone', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Colin Truett', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Wes Tucker', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Baylor Defense', 2, N' ', N'Healthy', N'Active'),
 (N'Hayden Arnold', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Isaiah Hankins', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Connor Hawkins', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Stone', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Palmer Williams', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Garrison Grimes', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Dylan Schaub', 2, N'Sophomore' , N'Healthy' , N'Active');
GO

-- BYU Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Gerry Bohanon', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Treyson Bourguet', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cole Hagen', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'McCae Hillstead', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Noah Lugo', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jake Retzlaff', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Jovesa Damuni', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Miles Davis', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Pokaiaua Haunga', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'LJ Martin', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Charles Miska', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sione I Moa', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Enoch Nawahine', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Hinckley Ropati', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Weston Covey', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kody Epps', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Cody Hagen', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jarinn Kalama', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Parker Kingston', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Darius Lassiter', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Keelan Marion', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Dominique McKenzie', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tei Nacua', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jojo Phillips', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Rowan Reay', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Chase Roberts', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Marquis Taliulu', 12, N'--' , N'Healthy' , N'Active'),
 (N'Tyler West', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Prince Zombo', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Bowers', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Nason Coleman', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ethan Erickson', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Mason Fakahua', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Keanu Hill', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Noah Moeaki', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Anthony Olsen', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ray Paulo', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Ryner Swanson', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mata''ava Ta''ase', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Will Zundel', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joe Brown', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kaden Chidester', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'David Clifford', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sam Dawe', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jake Eichorn', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Caleb Etienne', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Jake Griffin', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sione Hingano', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Isaiah Jatta', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Weston Jones', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brayden Keim', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Weylin Lapuaho', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Austin Leausa', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Sonny Makasini', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Bruce Mitchell', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jackson Nelson', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Trevin Ostler', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Connor Pay', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Trevor Pay', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ikinasio Tupou', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'BYU Defense', 12, N' ', N'Healthy', N'Active'),
 (N'Matthias Dunn', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Will Ferrin', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Landon Rehkow', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sam Vander Haar', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dalton Riggs', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cannon Skidmore', 12, N'Freshman' , N'Healthy' , N'Active');
GO

-- Cincinnati Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Jacob Hoying', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Samaj Jones', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Will Kocher', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brady Lichtenberg', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Brendan Sorsby', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Danny Stoddard', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jakorion Caffey', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Manny Covey', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Victor Dawson', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Brian Doneghy II', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Corey Kiner', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Evan Pryor', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Chance Williams', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Dakarai Anderson', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sterling Berkhalter', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Xzavier Henderson', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Barry Jackson Jr.', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tony Johnson', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Elijah Jones', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Zane Kinsey', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jamoi Mayes', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Michael Mussari', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Evan Prater', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Tyrin Smith', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Aaron Turner', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Kale Woodburn', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joey Beljan', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Gavin Grover', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael McCalmont', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Joe Royer', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Francis Sherman', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Lyviel Waters', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Devyn Zahursky', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Deondre Buford', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Zac Clarke', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Grant Edgington', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Gavin Gerhardt', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Ethan Green', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jonathan Harder', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Luke Kandra', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Xavier Lozowicki', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Judea Milon', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Aiden Pastoriza', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'JP Schrieber', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Evan Tengesdahl', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dartanyan Tinsley', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Jake Wheelock', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Phillip Wilder', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'John Williams', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Cincinnati Defense', 3, N' ', N'Healthy', N'Active'),
 (N'Carter Brown', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Nathan Hawks', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Max Lemasters', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mason Fletcher', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Max Fletcher', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Brady Young', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'George Leibold', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jayden Perry', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Weston Simmons', 3, N'Freshman' , N'Healthy' , N'Active');
GO

-- Colorado Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Colton Allen', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dominiq Ponder', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Shedeur Sanders', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Ryan Staub', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Walter Taylor III', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Destin Wade', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Isaiah Augustave', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Titus Bautista', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dallan Hayden', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brandon Hood', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Charlie Offerdahl', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Christian Sarem', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Micah Welch', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tagert Bardin', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ronald Coleman', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jimmy Horn Jr.', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Travis Hunter', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Gavin Marsh', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kaleb Mathis', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Kam Mikell', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Drelon Miller', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Omarion Miller', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jordan Onovughe', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cordale Russell', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Will Sheppard', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Terrell Timmons Jr.', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Asaad Waseem', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Westbrook', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'LaJohntay Wester', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Sam Hart', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Brady Kopetz', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Morgan Pearson', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Antonio Posadas', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sav''ell Smalls', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Charlie Williams', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Yakiri Walker', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Hank Zilinskas', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Yahya Attia', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Brown', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Wyatt Hummel', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Tyler Johnson', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Payton Kirkland', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Zack Owens', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kahlil Benson', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Cash Cleveland', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Justin Mayers', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Ben Reznik', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Kardell Thomas', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Kareem Harden', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Phillip Houston', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Jordan Seaton', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Colorado Defense', 6, N' ', N'Healthy', N'Active'),
 (N'Jace Feely', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Daniel Gerlach', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Alejandro Mata', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Cristiano Palazzo', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Alexander Stoyanovich', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mark Vassett', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Camden Dempsey', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Kameron Hawkins', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Gabe Landers', 6, N'Sophomore' , N'Healthy' , N'Active');
GO

-- Houston Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Ui Ale', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Zeon Chriss', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Holman Edwards', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Caleb McMickle', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Donovan Smith', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Jake Sock', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Indiana Wijay', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'J''Marion Burnette', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'DJ Butler', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Parker Jenkins', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Tony Mathis Jr.', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Steve Polk', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Re''Shaun Sanford II', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sherman Smith', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Stacy Sneed', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Christian Bean', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Austin Bice', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dylan Caddle', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Aaron Davis', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Anthony Gangi', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Dylan Gayton', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Stephon Johnson', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Joseph Manjack IV', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Mekhi Mews', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Samuel Padgitt', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'JayShon Ridgle', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Marquis Shoulders', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Hunter Teichman', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ja''Ryan Wallace', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kolby White', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Devan Williams', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jonah Wilson', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Koby Young', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ivan Autenreith', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Matt Byrnes', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Maliq Carr', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Brock Foster', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Traville Frederick Jr.', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cedric Melton', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Jett Runion', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kaleb Thomas', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jayden York', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Torren Coppage-El', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Zion Taylor', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Nadame Tucker', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Cavan Tuley', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ezekiel Akin-Abiodun', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ray''Quan Bell', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cayden Bowie', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ricardo Cordova', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Larry Crawford', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Peyton Dunn', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Hingano Hautau', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Shamar Hobdy-Lee', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Demetrius Hunter', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Tank Jenkins', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Derek Joiner', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ronnell McLain', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'David Ndukwe', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Sam Secrest', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dakota White', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Jake Wiley', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Houston Defense', 11, N' ', N'Healthy', N'Active'),
 (N'Jonathan Dimas', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Trey Furey', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joseph Kim', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Martin', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Alex Abbott', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Liam Dougherty', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Raney', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jacob Garza', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Pierson Parent', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Justin Wood', 11, N'Freshman' , N'Healthy' , N'Active');
GO

-- Iowa State Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Rocco Becht', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Wyatt Bohm', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Major Cantrell', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tanner Hughes', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'JJ Kohl', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Connor Moberly', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Aiden Flora', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Hansen', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jaylon Jackson', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Dylan Lee', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Easton Miller', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'AJ Petersen', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Abu Sama III', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Charlie Whelpley', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Isaiah Alston', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Wyatt Archer', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kai Black', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Brown', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Tyler Claiborne', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brett Eskildsen', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Eli Green', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Jayden Higgins', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Daniel Jackson', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Beni Ngoyi', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaylin Noel', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Dominic Overby', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael Parkes', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dillon Ranck', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Robbins', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jonathan Vande Walle', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cooper Alexander', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Bjorn', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Benjamin Brahmer', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Gabe Burkle', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'CJ Hayden', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Andrew Keller', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Stevo Klotz', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Tyler Moore', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Keaton Roskop', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tripp Walsh', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dylan Barrett', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Brendan Black', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jim Bonifas', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Trevor Buhr', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'AJ Burton', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Easton Eledge', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Aidan Gilmore', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Gabe Greenlee', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Deylin Hasert', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brent Helton', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Wade Helton', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dontrell Holt', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jarrod Hufford', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Evan Ladwig', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Tyler Maro', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Tyler Miller', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'George Nahas', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'James Neal', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Carson Rhodes', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garret Rutledge', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Blaine Sandquist', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Isaiah Seymour', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jalen Travis', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Owen Westemeyer', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Iowa State Defense', 4, N' ', N'Healthy', N'Active'),
 (N'Jace T. Gilbert', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Kyle Konrardy', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Keegan Shackford', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Tyler Perkins', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Drew Clausen', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Drew Doyle', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Drake Knobloch', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jacob Lyftogt', 4, N'Freshman' , N'Healthy' , N'Active');
GO

-- K-State Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
 (N'Blake Barnett', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hudson Hutcheson', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Avery Johnson', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jacob Knuth', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ta''Quan Roberson', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Evan Cantu', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dylan Edwards', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'DJ Giddens', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Joe Jackson', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'JB Price', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'DeVon Rice', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'La''James White', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Ty Bowman', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Jayce Brown', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dante Cephas', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Andre Davis', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Trae Davis', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jadon Jackson', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Keagan Johnson', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Isaac Koch', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Sterling Lockett', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Zayden Martinez', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Erwin Nash', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Bryce Noernberg', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Quenton Rice', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Tre Spivey', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jacques Spradley-Demps', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Voth', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cooper Warren', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Will Anciaux', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garrett Harstad', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brayden Loftin', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Andrew Metzger', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garrett Oakley', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Andrew Sonner', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Will Swanson', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Blake Turner', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Justin Wolf', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Camden Beebe', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Drake Bequeaith', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Michael Capria', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Logan Cox', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jackson Fullmer', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Gus Hawkins', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sam Hecht', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Ryan Howard', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Alex Key', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Easton Kilty', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Andrew Leingang', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Kaedin Massey', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hadley Panzer', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'John Pastore', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Taylor Poitier', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Kyle Rakers', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Navarro Schunke', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Devin Vass', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joe Vickers', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carver Willis', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Brock Woolf', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Teagan Cobb', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Simon McClannan', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Leyton Simmering', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Chris Tennant', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Keane Bessert', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Andrew Johnson', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mason Olguin', 1, N'Junior' , N'Healthy' , N'Active');
GO

-- KU Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Cole Ballard', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'TJ Crews IV', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jalon Daniels', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Ben Easters', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Isaiah Marshall', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mikey Pauley', 5, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Daniel Hishaw Jr.', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Micah Johnson', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Torry Locklin', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Carson Morgan', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sevion Morrison', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Devin Neal', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Jack Schneider', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Harry Stewart III', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Johnny Thompson Jr.', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Lawrence Arnold', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Bryce Cohoon', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Donald Collier', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Doug Emilien', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Luke Grimm', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Griffin Koch', 5, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Keaton Kubecka', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hunter Luke', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mack Moeller', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Isreal Moses V', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Grant Muffenbier', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jarred Sample', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Quentin Skinner', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Trevor Wilson', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Tevita Ahoafi-Noa', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Carson Bruhn', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jared Casey', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Quinton Conley', 5, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Leyton Cure', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Jaden Hamm', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'DeShawn Hanika', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Trevor Kardell', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Max Muehlberger', 5, N'Sophomore' , N'Healthy' , N'Active'),
 (N'David Abajian', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kene Anene', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kobe Baynes', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Logan Brown', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Shane Bumgardner', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Bryce Cabeldue', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Calvin Clements', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dre Doiron', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Myles Ewell', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kael Farkes', 5, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Michael Ford Jr.', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Bryce Foster', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Nolan Gorczyca', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Amir Herring', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hank Kelly', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Carter Lavrusky', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'James Livingston', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Eli Richmond', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Darrell Simmons Jr.', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'De''Kedrick Sterns', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Harrison Utley', 5, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tabor Allen', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Owen Piepergerdes', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Charlie Weinrich', 5, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Grayden Addison', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Damon Greaves', 5, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Emory Duggar', 5, N'Junior' , N'Healthy' , N'Active'),
 (N'Luke Hosford', 5, N'Senior' , N'Healthy' , N'Active'),
 (N'Hollis Moeller', 5, N'Freshman' , N'Healthy' , N'Active');
GO

-- Oklahoma State Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Alan Bowman', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Zane Flores', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garret Rangel', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Maealiuaki Smith', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garret Wilson', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaden Allen-Hendrix', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hudson Devins', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Rodney Fields Jr.', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ollie Gordon II', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'AJ Green', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Trent Howland', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Seth Swirczynski', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Holden Thompson', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sesi Vailahi', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'C.J. Williams', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Bryce Drummond', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Luke McEndoo', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Jake Schultz', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Tykie Andrews', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Braden Baize', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cale Cabbiness', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Jaxon Deason', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Marcus Dockins Jr.', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Gavin Freeman', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Mason Gilkey', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cutter Greene', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tre Griffiths', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Camron Heard', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Da''Wain Lofton', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Rashod Owens', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Kyler Pearson', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Jalen Pope', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brennan Presley', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Talyn Shettron', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ayo Shotomide-King', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'De''Zhaun Stribling', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Heston Thompson', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ty Walls', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joe Bisso', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Josh Ford', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Foster', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Dominic Grein', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tabry Shettron', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Quinton Stewart', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Cole Birmingham', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Jason Brooks Jr.', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Dalton Cooper', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Davis Dotson', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jack Endean', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Isaia Glass', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Caleb Hackleman', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Calvin Harvey', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jarrett Henry', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Wyatt Holmes', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Aiden Isaacs', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ashton Isaacs', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Chauncey Johnson', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Austin Kawecki', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Nuku Mafi', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hilton Marsh', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Noah McKinney', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jamison Mejia', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joe Michalski', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Taylor Miterko', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Jakobe Sanders', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Wiley Sills', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jake Springfield', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Gage Stanaland', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Preston Wilson', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Oklahoma State Defense', 7, N' ', N'Healthy', N'Active'),
 (N'David Arriaga', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kason Shrum', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Drake Tabor', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Logan Ward', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Hudson Kaak', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Wes Pahl', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Aidan Davenport', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Shea Freibaum', 7, N'Sophomore' , N'Healthy' , N'Active');
GO

-- TCU Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Hauss Hejny', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Josh Hoover', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Hayden Parga', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jacob Porter', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ken Seals', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Brant Ahlfinger', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Trent Battle', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Derrick Carroll', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cam Cook', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Franklin Estrada II', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Dominique Johnson', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Nate Palmer', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jeremy Payne', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joe Pitchford', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Trey Sanders', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Jordyn Bailey', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Gekyle Baker', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Bech', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Parker Clark', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Keagan Cunningham', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Colton Dobson', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'JoJo Earle', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Major Everhart', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dozie Ezukanma', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Fletcher Fierro', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Braylon James', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hunter Krepp', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Joe Laterza', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Sutton Lee', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Eric McAlister', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Blake Nowell', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'JP Richardson', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Austin Scheets', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Steel Tobin', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Savion Williams', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Dylan Wright', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Chase Curtis', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Drake Dabney', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Lafayette Kaiuway', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cade Keith', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jax Porter', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'DJ Rogers', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Cole Snodgrass', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cade Bennett', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'James Brockermeyer', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Carson Bruno', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Samir Camacho', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Coltin Deery', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Gannon Gaubert', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Bless Harris', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Quinton Harris', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Wesley Harvey', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mitch Hodnett', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ryan Hughes', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Connor Lingren', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jackson McNeff', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mike Nichols', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Cooper Powers', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Robby Rochester', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Riley Self', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Tobias Steppes', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mike Stoker', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Remington Strickland', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Ben Taylor-Whitfield', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Lucas Vargas-Diaz', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hudson White', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'TCU Defense', 8, N' ', N'Healthy', N'Active'),
 (N'Kyle Lemmermann', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Nate McCashland', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Caleb Sempebwa', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Easton Black', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ethan Craw', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Cal Keeler', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brent Matiscik', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Jax Thompson', 8, N'Freshman' , N'Healthy' , N'Active');
GO

-- Texas Tech Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Cameran Brown', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Will Hammond', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Behren Morton', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Jake Strong', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tahj Brooks', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Cameron Dickey', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Adam Hill', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaden Morris', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cam''Ron Valdez', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'J''Koby Williams', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brady Boyd', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Jordan Brown', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'D.J. Crest', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Caleb Douglas', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Coy Eakin', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Drew Hocutt', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Micah Hudson', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'L.J. Johnson Jr.', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Josh Kelly', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Drae McCray', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Aiden Meeks', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Price Morgan', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Curtis Murillo', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Chandlin Myers', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyson Turner', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kelby Valsin', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'T.J. West', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Haydon Wiginton', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Jalin Conyers', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Jack Esparza', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Trey Jackson', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jason Llewellyn', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Johncarlos Miller II', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Charles Robinson', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Mason Tharp', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Ty Buchanan', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Kaden Carr', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Davion Carter', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Ellis Davis', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Nick Fattig', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Holton Hendrix', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Hildebrand', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaxon Hughes', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Jurrien Loftin', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dalton Merryman', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Garrett Morphis', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Murray', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jacob Ponton', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sterling Porcher', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Caleb Rodkey', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Maurice Rodriques', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Caleb Rogers', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Vinny Sciury', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Dylan Shaw', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Daniel Sill', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'D''Anthis Upshaw', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sheridan Wilson', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'TCU Defense', 8, N' ', N'Healthy', N'Active'),
 (N'Reese Burkhardt', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Gino Garcia', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Stone Harrington', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jack Burgess', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Kaden Turner', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Knotts', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Rylan Vagana', 9, N'Freshman' , N'Healthy' , N'Active');
GO

-- UCF Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Jacurri Brown', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'EJ Colson', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brock Hansel', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'KJ Jefferson', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Dylan Rizk', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Riley Trujillo', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Peny Boone', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Preston Foreman', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Stacy Gage', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'RJ Harvey', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Kam Ingram', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Myles Montgomery', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Johnny Richardson', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Tyler Wrenn', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jarrad Baker', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Jordyn Bridgewater', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Hinshaw', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kobe Hudson', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Ja''Varrius Johnson', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Jacoby Jones', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Chauncey Magwood', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Tyree Patterson', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Bredell Richardson', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Caleb Rollerson', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kason Stokes', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Xavier Townsend', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Trent Whittemore', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Dwartney Wortham', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Reece Adkins', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Jordan Davis', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Kylan Fox', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Evan Morris', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Randy Pittman Jr.', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Grant Stevens', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Thomas Wadsworth', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Patrick Barnett', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Jabari Brooks', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Johnathan Cline', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Colin Cook', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Keyon Cox', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Wes Dorsey', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Waltclaire Flynn', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Thomas Gearity', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ethan Higgins', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Shaheem Hill', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Amari Kight', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Cameron Kinnie', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Caden Kitler', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Chase Malamala', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Marcellus Marshall', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Adrian Medley', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Andrew Phelan', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Matthew Prigmore', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Paul Rubelt', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Keegan Smith', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'UCF Defense', 10, N' ', N'Healthy', N'Active'),
 (N'Colton Boomer', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Kevin Carrigan', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Grant Reddick', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael Carter', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Mitch McCarthy', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Jack Bernstein', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Aidan Fedigan', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Gage King', 10, N'Senior' , N'Healthy' , N'Active');
GO

-- Utah Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Luke Bottari', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Sam Huard', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Cameron Rising', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Brandon Rose', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Isaac Wilson', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hunter Andrews', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Micah Bernard', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Laython Biddle', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaylon Glover', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Mike Mitchell', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Omar Shah', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dijon Stanley', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Charlie Vincent', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Anthony Woods', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Damien Alford', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Luca Caldarella', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Matt Clark', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Rayshawn Glover', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Kaimana Hanohano', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Diezel Kamoku', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Taeshaun Lyons', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Munir McClain', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Jett Meine', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cameron Mitchell', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Money Parks', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Mycah Pittman', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Peyton Rice', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dorian Singer', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'David Washington', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Zacharyus Williams', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Daidren Zipperer', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dallen Bentley', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Justice Brusatto', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Spencer Clegg', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Frankie Goodson', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'CJ Jacobsen', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Landen King', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Brant Kuithe', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Caleb Lohner', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Carsen Ryan', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Miki Suguturaga', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Roger Alderman', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Spencer Fano', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Isaiah Garcia', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Alex Harrison', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Lukas Jackson', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Falcon Kaumatule', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Jaren Kump', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Caleb Lomu', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Johnny Maea', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Shintaro Mann', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Solatoa Moea''i', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Michael Mokofisi', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Brennan Molina', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Keith Olson', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Reece Parmenter', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kamilo Raass', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Alma Taleni', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tanoa Togiai', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Zereoue Williams', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Utah Defense', 16, N' ', N'Healthy', N'Active'),
 (N'Cole Becker', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Joey Cheek', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Trey Coleman', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Bouwmeester', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Elliot Janish', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Logan Castor', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'JT Greep', 16, N'Senior' , N'Healthy' , N'Active');
GO

-- West Virginia Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Ryder Burton', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Crist', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Abe Fenwick', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garrett Greene', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Scott Kean', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Nicco Marchiol', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Khalil Wilkins', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaylen Anderson', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Clay Ash', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Murphy Clement', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'CJ Donaldson Jr.', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Trae''von Dunbar', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Diore Hubbard', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Judah Price', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jahiem White', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Colin McBee', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jaden Bray', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Hudson Clement', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'C.J. Cole', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Dom Collins', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mykel Davis', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Evans', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ric''Darious Farmer', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Preston Fox', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Rodney Gallagher III', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'TJ Johnson', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Andrew Phares', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Traylon Ray', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brandon Rehmann', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Justin Robinson', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Jarel Williams', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Noah Braham', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Treylan Davis', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Will Dixon', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Greg Genross', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Jack Sammarco', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kole Taylor', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Kyle Altuner', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Lucas Austin', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Xavier Bausley', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Bryce Biggs', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Aiden Ellis', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Griffin Fogle', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Wesley Hancock', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ja''Quay Hubbard', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Andreas Hunter', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Nick Krahe', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Landen Livingston', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Nick Malone', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Wyatt Milum', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Tomas Rimac', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Justin Terry', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sullivan Weidman', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Johnny Williams IV', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brandon Yates', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Cooper Young', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'West Virginia Defense', 13, N' ', N'Healthy', N'Active'),
 (N'Nate Flower', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael Hayes II', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'RJ Kocan', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Casey Stanley', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Leighton Bechdel', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Luke Savino', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Oliver Straw', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Ronan Swope', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Austin Brinkman', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Macguire Moss', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Kaden Seller', 13, N'Freshman' , N'Healthy' , N'Active');
GO