USE Team13;
GO

-- Arizona Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Mason Bray', 1, N'Freshman' , N'Healthy' , N'Active'), -- 1
 (N'Adam Damante', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brayden Dorman', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Noah Fifita', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Anthony Garcia', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cole Tannenbaum', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Quali Conley', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Jacory Croskey-Merritt', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Brandon Johnson', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kayden Luke', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Rayshon Luke', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Kedrick Reescano', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Anthony Wilhite', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jaden Clark', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Sam Graci-Glazer', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Rex Haynes', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jackson Holman', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Chris Hunter', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Devin Hyatt', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'AJ Jones', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Montana Lemonious-Craig', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Jordan McCord III', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tetairoa McMillan', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Reymello Murphy', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Julius Oliver', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jeremiah Patterson', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Brandon Phelps', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Malachi Riley', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Keyan Burnett', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'John Hart', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Roberto Miranda', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Sam Olson', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Tyler Powell', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dylan Tapley', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dorian Thomas', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Josh Baker', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Joey Capra', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Alexander Doost', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tylen Gonzalez', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'JT Hand', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Matthew Lado', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Leif Magnuson', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Shancco Matautia', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Wendell Moe Jr.', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Elijha Payne', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Raymond Pulido', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jonah Rodriguez', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jonah Savaiinaea', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Ryan Stewart', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Grayson Stovall', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Rhino Tapa''atoutai', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Zarius Wells', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael Wooten', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Arizona Defense', 1, N' ', N'Healthy', N'Active'),
 (N'Tyler Loop', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Michael Salgado-Medina', 1, N'Freshman' , N'Healthy' , N'Active'),
 (N'Lachlan Bruce', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Jordan Forbes', 1, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cash Peterman', 1, N'Junior' , N'Healthy' , N'Active'),
 (N'Justin Holloway', 1, N'Senior' , N'Healthy' , N'Active'),
 (N'Trey Naughton', 1, N'Sophomore' , N'Healthy' , N'Active'); -- 61
GO

-- Arizona State Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Trenton Bourguet', 2, N'Senior' , N'Healthy' , N'Active'), -- 62
 (N'Navi Bruzon', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Christian Hunt', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Laskaris', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sam Leavitt', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jeff Sims', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'DeCarlos Brooks', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Kyson Brown', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Raleek Brown', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jason Brown Jr.', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Alton McCaskill', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Cam Skattebo', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Kaleb Black', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Coben Bourguet', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Armon Collins', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Deric English', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Derek Eusebio', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Xavier Guillory', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Korbin Hendrix', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Malik McClain', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Troy Omeire', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Zechariah Sample', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jake Smith', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Justice Spann', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Melquan Stovall', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Jordyn Tyson', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Max Ware', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jamaal Young II', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Coleson Arends', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Markeston Douglas', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Jayden Fortier', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'James Giggey', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cameron Harpole', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Chamon Metayer', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Sinjin Schmitt', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Josh Atkins', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Emmit Bohle', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Cade Briggs', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Connor Cameron', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ben Coleman', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Luis Cordova', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Leif Fautanu', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Colby Garvin', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Kaden Haeckel', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Max Iheanachor', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Sirri Kandiyeli', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Keim', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Terrell Kim', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jalen Klemm', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brandon Lloyd', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Sean Na''a', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Keona Peat', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Makua Pule', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kyle Scott', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Joey Su''a', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Semisi Tonga', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Bram Walden', 2, N'Junior' , N'Healthy' , N'Active'),
 (N'Champ Westbrooks', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Arizona State Defense', 2, N' ', N'Healthy', N'Active'),
 (N'Ian Hershey', 2, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Carston Kieffer', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Parker Lewis', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Kanyon Floyd', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Race Mahlum', 2, N'Senior' , N'Healthy' , N'Active'),
 (N'Cole Marszalek', 2, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Wigglesworth', 2, N'Sophomore' , N'Healthy' , N'Active'); -- 127
GO

-- Baylor Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Nate Bennett', 3, N'Freshman' , N'Healthy' , N'Active'), -- 128
 (N'Dequan Finn', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Brayson McHenry', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Sawyer Robertson', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Cade Tessier', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joseph Dodds', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joseph Hagman', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dawson Pendergrass', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Richard Reese', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Dominic Richardson', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Bryson Washington', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Baird', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Monaray Baldwin', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Jamaal Bell', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Cameron Bonner', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Jonah Burton', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Josh Cameron', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Isaiah Davis', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Daniel Edeni', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Micah Gifford', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ashtyn Hawkins', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Ketron Jackson Jr.', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Jadon Porter', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hal Presley', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Seth Weller', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Kelsey Johnson', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Matthew Klopfenstein', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cody Mladenka', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Hawkins Polley', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael Trigg', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Gavin Yates', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Omar Aigbedion', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Campbell Barrington', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Gavin Byers', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Alvin Ebosele', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Sidney Fugar', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Ka''Marii Landers', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Ryan Lengyel', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Coleton Price', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Isaiah Robinson', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kaden Sieracki', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Koltin Sieracki', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Wyatt Swaner', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Colton Thomasson', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Sean Thompkins', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cayden Tone', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Colin Truett', 3, N'Senior' , N'Healthy' , N'Active'),
 (N'Wes Tucker', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Baylor Defense', 3, N' ', N'Healthy', N'Active'),
 (N'Hayden Arnold', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Isaiah Hankins', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Connor Hawkins', 3, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Stone', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Palmer Williams', 3, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Garrison Grimes', 3, N'Junior' , N'Healthy' , N'Active'),
 (N'Dylan Schaub', 3, N'Sophomore' , N'Healthy' , N'Active'); -- 183
GO

-- BYU Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Gerry Bohanon', 4, N'Senior' , N'Healthy' , N'Active'), -- 184
 (N'Treyson Bourguet', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cole Hagen', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'McCae Hillstead', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Noah Lugo', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jake Retzlaff', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Jovesa Damuni', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Miles Davis', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Pokaiaua Haunga', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'LJ Martin', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Charles Miska', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sione I Moa', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Enoch Nawahine', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Hinckley Ropati', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Weston Covey', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kody Epps', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Cody Hagen', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jarinn Kalama', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Parker Kingston', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Darius Lassiter', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Keelan Marion', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Dominique McKenzie', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tei Nacua', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jojo Phillips', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Rowan Reay', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Chase Roberts', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Marquis Taliulu', 4, N'--' , N'Healthy' , N'Active'),
 (N'Tyler West', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Prince Zombo', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Bowers', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Nason Coleman', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ethan Erickson', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Mason Fakahua', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Keanu Hill', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Noah Moeaki', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Anthony Olsen', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ray Paulo', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Ryner Swanson', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mata''ava Ta''ase', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Will Zundel', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joe Brown', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kaden Chidester', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'David Clifford', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sam Dawe', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jake Eichorn', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Caleb Etienne', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Jake Griffin', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sione Hingano', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Isaiah Jatta', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Weston Jones', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brayden Keim', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Weylin Lapuaho', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Austin Leausa', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Sonny Makasini', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Bruce Mitchell', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jackson Nelson', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Trevin Ostler', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Connor Pay', 4, N'Senior' , N'Healthy' , N'Active'),
 (N'Trevor Pay', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ikinasio Tupou', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'BYU Defense', 4, N' ', N'Healthy', N'Active'),
 (N'Matthias Dunn', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Will Ferrin', 4, N'Junior' , N'Healthy' , N'Active'),
 (N'Landon Rehkow', 4, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sam Vander Haar', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dalton Riggs', 4, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cannon Skidmore', 4, N'Freshman' , N'Healthy' , N'Active'); -- 250
GO

-- Cincinnati Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Jacob Hoying', 5,N'Junior' , N'Healthy' , N'Active'), -- 251
 (N'Samaj Jones', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Will Kocher', 5,N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brady Lichtenberg', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Brendan Sorsby', 5,N'Sophomore' , N'Healthy' , N'Active'),
 (N'Danny Stoddard', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Jakorion Caffey', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Manny Covey', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Victor Dawson', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Brian Doneghy II', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Corey Kiner', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Evan Pryor', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Chance Williams', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Dakarai Anderson', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Sterling Berkhalter', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Xzavier Henderson', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Barry Jackson Jr.', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Tony Johnson', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Elijah Jones', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Zane Kinsey', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Jamoi Mayes', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Michael Mussari', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Evan Prater', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Tyrin Smith', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Aaron Turner', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Kale Woodburn', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Joey Beljan', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Gavin Grover', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael McCalmont', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Joe Royer', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Francis Sherman', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Lyviel Waters', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Devyn Zahursky', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Deondre Buford', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Zac Clarke', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Grant Edgington', 5,N'Sophomore' , N'Healthy' , N'Active'),
 (N'Gavin Gerhardt', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Ethan Green', 5,N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jonathan Harder', 5,N'Sophomore' , N'Healthy' , N'Active'),
 (N'Luke Kandra', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Xavier Lozowicki', 5,N'Sophomore' , N'Healthy' , N'Active'),
 (N'Judea Milon', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Aiden Pastoriza', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'JP Schrieber', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Evan Tengesdahl', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Dartanyan Tinsley', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Jake Wheelock', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Phillip Wilder', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'John Williams', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Cincinnati Defense', 5,N' ', N'Healthy', N'Active'),
 (N'Carter Brown', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Nathan Hawks', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Max Lemasters', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Mason Fletcher', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Max Fletcher', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'Brady Young', 5,N'Junior' , N'Healthy' , N'Active'),
 (N'George Leibold', 5,N'Freshman' , N'Healthy' , N'Active'),
 (N'Jayden Perry', 5,N'Senior' , N'Healthy' , N'Active'),
 (N'Weston Simmons', 5,N'Freshman' , N'Healthy' , N'Active'); -- 309
GO

-- Colorado Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Colton Allen', 6, N'Sophomore' , N'Healthy' , N'Active'), -- 310
 (N'Dominiq Ponder', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Shedeur Sanders', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Ryan Staub', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Walter Taylor III', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Destin Wade', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Isaiah Augustave', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Titus Bautista', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dallan Hayden', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brandon Hood', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Charlie Offerdahl', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Christian Sarem', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Micah Welch', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tagert Bardin', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ronald Coleman', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jimmy Horn Jr.', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Travis Hunter', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Gavin Marsh', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kaleb Mathis', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Kam Mikell', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Drelon Miller', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Omarion Miller', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jordan Onovughe', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cordale Russell', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Will Sheppard', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Terrell Timmons Jr.', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Asaad Waseem', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Westbrook', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'LaJohntay Wester', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Sam Hart', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Brady Kopetz', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Morgan Pearson', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Antonio Posadas', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sav''ell Smalls', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Charlie Williams', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Yakiri Walker', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Hank Zilinskas', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Yahya Attia', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Brown', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Wyatt Hummel', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Tyler Johnson', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Payton Kirkland', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Zack Owens', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kahlil Benson', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Cash Cleveland', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Justin Mayers', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Ben Reznik', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Kardell Thomas', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Kareem Harden', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Phillip Houston', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Jordan Seaton', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Colorado Defense', 6, N' ', N'Healthy', N'Active'),
 (N'Jace Feely', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Daniel Gerlach', 6, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Alejandro Mata', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Cristiano Palazzo', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Alexander Stoyanovich', 6, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mark Vassett', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Camden Dempsey', 6, N'Junior' , N'Healthy' , N'Active'),
 (N'Kameron Hawkins', 6, N'Senior' , N'Healthy' , N'Active'),
 (N'Gabe Landers', 6, N'Sophomore' , N'Healthy' , N'Active'); -- 370
GO

-- Houston Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Ui Ale', 7, N'Sophomore' , N'Healthy' , N'Active'), -- 371
 (N'Zeon Chriss', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Holman Edwards', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Caleb McMickle', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Donovan Smith', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Jake Sock', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Indiana Wijay', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'J''Marion Burnette', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'DJ Butler', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Parker Jenkins', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Tony Mathis Jr.', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Steve Polk', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Re''Shaun Sanford II', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sherman Smith', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Stacy Sneed', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Christian Bean', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Austin Bice', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dylan Caddle', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Aaron Davis', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Anthony Gangi', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Dylan Gayton', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Stephon Johnson', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Joseph Manjack IV', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Mekhi Mews', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Samuel Padgitt', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'JayShon Ridgle', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Marquis Shoulders', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Hunter Teichman', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ja''Ryan Wallace', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kolby White', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Devan Williams', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jonah Wilson', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Koby Young', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ivan Autenreith', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Matt Byrnes', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Maliq Carr', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Brock Foster', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Traville Frederick Jr.', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cedric Melton', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Jett Runion', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kaleb Thomas', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jayden York', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Torren Coppage-El', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Zion Taylor', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Nadame Tucker', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Cavan Tuley', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ezekiel Akin-Abiodun', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ray''Quan Bell', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cayden Bowie', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ricardo Cordova', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Larry Crawford', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Peyton Dunn', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Hingano Hautau', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Shamar Hobdy-Lee', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Demetrius Hunter', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Tank Jenkins', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Derek Joiner', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ronnell McLain', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'David Ndukwe', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Sam Secrest', 7, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dakota White', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Jake Wiley', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Houston Defense', 7, N' ', N'Healthy', N'Active'),
 (N'Jonathan Dimas', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Trey Furey', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joseph Kim', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Martin', 7, N'Senior' , N'Healthy' , N'Active'),
 (N'Alex Abbott', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Liam Dougherty', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Raney', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jacob Garza', 7, N'Junior' , N'Healthy' , N'Active'),
 (N'Pierson Parent', 7, N'Freshman' , N'Healthy' , N'Active'),
 (N'Justin Wood', 7, N'Freshman' , N'Healthy' , N'Active'); -- 443
GO

-- Iowa State Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Rocco Becht', 8, N'Sophomore' , N'Healthy' , N'Active'), -- 444
 (N'Wyatt Bohm', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Major Cantrell', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tanner Hughes', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'JJ Kohl', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Connor Moberly', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Aiden Flora', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Hansen', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jaylon Jackson', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Dylan Lee', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Easton Miller', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'AJ Petersen', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Abu Sama III', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Charlie Whelpley', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Isaiah Alston', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Wyatt Archer', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kai Black', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Brown', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Tyler Claiborne', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brett Eskildsen', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Eli Green', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Jayden Higgins', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Daniel Jackson', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Beni Ngoyi', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaylin Noel', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Dominic Overby', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael Parkes', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dillon Ranck', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Robbins', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jonathan Vande Walle', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cooper Alexander', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Bjorn', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Benjamin Brahmer', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Gabe Burkle', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'CJ Hayden', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Andrew Keller', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Stevo Klotz', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Tyler Moore', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Keaton Roskop', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tripp Walsh', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dylan Barrett', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Brendan Black', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jim Bonifas', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Trevor Buhr', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'AJ Burton', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Easton Eledge', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Aidan Gilmore', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Gabe Greenlee', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Deylin Hasert', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brent Helton', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Wade Helton', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dontrell Holt', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jarrod Hufford', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Evan Ladwig', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Tyler Maro', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Tyler Miller', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'George Nahas', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'James Neal', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Carson Rhodes', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garret Rutledge', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Blaine Sandquist', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Isaiah Seymour', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jalen Travis', 8, N'Senior' , N'Healthy' , N'Active'),
 (N'Owen Westemeyer', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Iowa State Defense', 8, N' ', N'Healthy', N'Active'),
 (N'Jace T. Gilbert', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Kyle Konrardy', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Keegan Shackford', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Tyler Perkins', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Drew Clausen', 8, N'Junior' , N'Healthy' , N'Active'),
 (N'Drew Doyle', 8, N'Freshman' , N'Healthy' , N'Active'),
 (N'Drake Knobloch', 8, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jacob Lyftogt', 8, N'Freshman' , N'Healthy' , N'Active'); -- 516
GO

-- K-State Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
 (N'Blake Barnett', 9, N'Freshman' , N'Healthy' , N'Active'), -- 517
 (N'Hudson Hutcheson', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Avery Johnson', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jacob Knuth', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ta''Quan Roberson', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Evan Cantu', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dylan Edwards', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'DJ Giddens', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Joe Jackson', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'JB Price', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'DeVon Rice', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'La''James White', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Ty Bowman', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Jayce Brown', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dante Cephas', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Andre Davis', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Trae Davis', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jadon Jackson', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Keagan Johnson', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Isaac Koch', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Sterling Lockett', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Zayden Martinez', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Erwin Nash', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Bryce Noernberg', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Quenton Rice', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Tre Spivey', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jacques Spradley-Demps', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Voth', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cooper Warren', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Will Anciaux', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garrett Harstad', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brayden Loftin', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Andrew Metzger', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garrett Oakley', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Andrew Sonner', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Will Swanson', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Blake Turner', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Justin Wolf', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Camden Beebe', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Drake Bequeaith', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Michael Capria', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Logan Cox', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jackson Fullmer', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Gus Hawkins', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sam Hecht', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Ryan Howard', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Alex Key', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Easton Kilty', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Andrew Leingang', 9, N'Junior' , N'Healthy' , N'Active'),
 (N'Kaedin Massey', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hadley Panzer', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'John Pastore', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Taylor Poitier', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Kyle Rakers', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Navarro Schunke', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Devin Vass', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joe Vickers', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carver Willis', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Brock Woolf', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kansas State Defense', 9, N' ', N'Healthy', N'Active'),
 (N'Teagan Cobb', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Simon McClannan', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Leyton Simmering', 9, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Chris Tennant', 9, N'Senior' , N'Healthy' , N'Active'),
 (N'Keane Bessert', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Andrew Johnson', 9, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mason Olguin', 9, N'Junior' , N'Healthy' , N'Active'); -- 583
GO

-- KU Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Cole Ballard', 10, N'Freshman' , N'Healthy' , N'Active'), -- 584
 (N'TJ Crews IV', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jalon Daniels', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Ben Easters', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Isaiah Marshall', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mikey Pauley', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Daniel Hishaw Jr.', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Micah Johnson', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Torry Locklin', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Carson Morgan', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sevion Morrison', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Devin Neal', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Jack Schneider', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Harry Stewart III', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Johnny Thompson Jr.', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Lawrence Arnold', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Bryce Cohoon', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Donald Collier', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Doug Emilien', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Luke Grimm', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Griffin Koch', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Keaton Kubecka', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hunter Luke', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mack Moeller', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Isreal Moses V', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Grant Muffenbier', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jarred Sample', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Quentin Skinner', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Trevor Wilson', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Tevita Ahoafi-Noa', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Carson Bruhn', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jared Casey', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Quinton Conley', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Leyton Cure', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Jaden Hamm', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'DeShawn Hanika', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Trevor Kardell', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Max Muehlberger', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'David Abajian', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kene Anene', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kobe Baynes', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Logan Brown', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Shane Bumgardner', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Bryce Cabeldue', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Calvin Clements', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dre Doiron', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Myles Ewell', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kael Farkes', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Michael Ford Jr.', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Bryce Foster', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Nolan Gorczyca', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Amir Herring', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hank Kelly', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Carter Lavrusky', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'James Livingston', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Eli Richmond', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Darrell Simmons Jr.', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'De''Kedrick Sterns', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Harrison Utley', 10, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kansas Defense', 10, N' ', N'Healthy', N'Active'),
 (N'Tabor Allen', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Owen Piepergerdes', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Charlie Weinrich', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Grayden Addison', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Damon Greaves', 10, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Emory Duggar', 10, N'Junior' , N'Healthy' , N'Active'),
 (N'Luke Hosford', 10, N'Senior' , N'Healthy' , N'Active'),
 (N'Hollis Moeller', 10, N'Freshman' , N'Healthy' , N'Active'); -- 651
GO

-- Oklahoma State Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Alan Bowman', 11, N'Senior' , N'Healthy' , N'Active'), -- 652
 (N'Zane Flores', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garret Rangel', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Maealiuaki Smith', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garret Wilson', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaden Allen-Hendrix', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hudson Devins', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Rodney Fields Jr.', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ollie Gordon II', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'AJ Green', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Trent Howland', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Seth Swirczynski', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Holden Thompson', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sesi Vailahi', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'C.J. Williams', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Bryce Drummond', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Luke McEndoo', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Jake Schultz', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Tykie Andrews', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Braden Baize', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cale Cabbiness', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Jaxon Deason', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Marcus Dockins Jr.', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Gavin Freeman', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Mason Gilkey', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cutter Greene', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tre Griffiths', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Camron Heard', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Da''Wain Lofton', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Rashod Owens', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Kyler Pearson', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Jalen Pope', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brennan Presley', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Talyn Shettron', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ayo Shotomide-King', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'De''Zhaun Stribling', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Heston Thompson', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ty Walls', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joe Bisso', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Josh Ford', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Foster', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Dominic Grein', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tabry Shettron', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Quinton Stewart', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Cole Birmingham', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Jason Brooks Jr.', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Dalton Cooper', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Davis Dotson', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jack Endean', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Isaia Glass', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Caleb Hackleman', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Calvin Harvey', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jarrett Henry', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Wyatt Holmes', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Aiden Isaacs', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ashton Isaacs', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Chauncey Johnson', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Austin Kawecki', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Nuku Mafi', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hilton Marsh', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Noah McKinney', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jamison Mejia', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joe Michalski', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Taylor Miterko', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Jakobe Sanders', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Wiley Sills', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jake Springfield', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Gage Stanaland', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Preston Wilson', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Oklahoma State Defense', 11, N' ', N'Healthy', N'Active'),
 (N'David Arriaga', 11, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kason Shrum', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Drake Tabor', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Logan Ward', 11, N'Junior' , N'Healthy' , N'Active'),
 (N'Hudson Kaak', 11, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Wes Pahl', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Aidan Davenport', 11, N'Senior' , N'Healthy' , N'Active'),
 (N'Shea Freibaum', 11, N'Sophomore' , N'Healthy' , N'Active'); -- 729
GO

-- TCU Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Hauss Hejny', 12, N'Freshman' , N'Healthy' , N'Active'), -- 730
 (N'Josh Hoover', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Hayden Parga', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jacob Porter', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ken Seals', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Brant Ahlfinger', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Trent Battle', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Derrick Carroll', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cam Cook', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Franklin Estrada II', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Dominique Johnson', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Nate Palmer', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jeremy Payne', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Joe Pitchford', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Trey Sanders', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Jordyn Bailey', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Gekyle Baker', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Bech', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Parker Clark', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Keagan Cunningham', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Colton Dobson', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'JoJo Earle', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Major Everhart', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dozie Ezukanma', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Fletcher Fierro', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Braylon James', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hunter Krepp', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Joe Laterza', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Sutton Lee', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Eric McAlister', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Blake Nowell', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'JP Richardson', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Austin Scheets', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Steel Tobin', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Savion Williams', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Dylan Wright', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Chase Curtis', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Drake Dabney', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Lafayette Kaiuway', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cade Keith', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jax Porter', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'DJ Rogers', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Cole Snodgrass', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Cade Bennett', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'James Brockermeyer', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Carson Bruno', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Samir Camacho', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Coltin Deery', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Gannon Gaubert', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Bless Harris', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Quinton Harris', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Wesley Harvey', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mitch Hodnett', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ryan Hughes', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Connor Lingren', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jackson McNeff', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mike Nichols', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Cooper Powers', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Robby Rochester', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Riley Self', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Tobias Steppes', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mike Stoker', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Remington Strickland', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Ben Taylor-Whitfield', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Lucas Vargas-Diaz', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hudson White', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'TCU Defense', 12, N' ', N'Healthy', N'Active'),
 (N'Kyle Lemmermann', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Nate McCashland', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Caleb Sempebwa', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Easton Black', 12, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ethan Craw', 12, N'Junior' , N'Healthy' , N'Active'),
 (N'Cal Keeler', 12, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brent Matiscik', 12, N'Senior' , N'Healthy' , N'Active'),
 (N'Jax Thompson', 12, N'Freshman' , N'Healthy' , N'Active'); -- 804
GO

-- Texas Tech Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Cameran Brown', 13, N'Sophomore' , N'Healthy' , N'Active'), -- 805
 (N'Will Hammond', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Behren Morton', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Jake Strong', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tahj Brooks', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Cameron Dickey', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Adam Hill', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaden Morris', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cam''Ron Valdez', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'J''Koby Williams', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brady Boyd', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Jordan Brown', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'D.J. Crest', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Caleb Douglas', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Coy Eakin', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Drew Hocutt', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Micah Hudson', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'L.J. Johnson Jr.', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Josh Kelly', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Drae McCray', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Aiden Meeks', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Price Morgan', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Curtis Murillo', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Chandlin Myers', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyson Turner', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kelby Valsin', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'T.J. West', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Haydon Wiginton', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Jalin Conyers', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Jack Esparza', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Trey Jackson', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jason Llewellyn', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Johncarlos Miller II', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Charles Robinson', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Mason Tharp', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Ty Buchanan', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Kaden Carr', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Davion Carter', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Ellis Davis', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Nick Fattig', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Holton Hendrix', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Hildebrand', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaxon Hughes', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Jurrien Loftin', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Dalton Merryman', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Garrett Morphis', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Murray', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jacob Ponton', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sterling Porcher', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Caleb Rodkey', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Maurice Rodriques', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Caleb Rogers', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Vinny Sciury', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Dylan Shaw', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Daniel Sill', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'D''Anthis Upshaw', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sheridan Wilson', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Texas Tech Defense', 13, N' ', N'Healthy', N'Active'),
 (N'Reese Burkhardt', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Gino Garcia', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Stone Harrington', 13, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jack Burgess', 13, N'Junior' , N'Healthy' , N'Active'),
 (N'Kaden Turner', 13, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jackson Knotts', 13, N'Senior' , N'Healthy' , N'Active'),
 (N'Rylan Vagana', 13, N'Freshman' , N'Healthy' , N'Active'); -- 869
GO

-- UCF Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Jacurri Brown', 14, N'Sophomore' , N'Healthy' , N'Active'), -- 870
 (N'EJ Colson', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brock Hansel', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'KJ Jefferson', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Dylan Rizk', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Riley Trujillo', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Peny Boone', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Preston Foreman', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Stacy Gage', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'RJ Harvey', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Kam Ingram', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Myles Montgomery', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Johnny Richardson', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Tyler Wrenn', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jarrad Baker', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Jordyn Bridgewater', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Carson Hinshaw', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kobe Hudson', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Ja''Varrius Johnson', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Jacoby Jones', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Chauncey Magwood', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Tyree Patterson', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Bredell Richardson', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Caleb Rollerson', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kason Stokes', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Xavier Townsend', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Trent Whittemore', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Dwartney Wortham', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Reece Adkins', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Jordan Davis', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Kylan Fox', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Evan Morris', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Randy Pittman Jr.', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Grant Stevens', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Thomas Wadsworth', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Patrick Barnett', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Jabari Brooks', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Johnathan Cline', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Colin Cook', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Keyon Cox', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Wes Dorsey', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Waltclaire Flynn', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Thomas Gearity', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ethan Higgins', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Shaheem Hill', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Amari Kight', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Cameron Kinnie', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Caden Kitler', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Chase Malamala', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Marcellus Marshall', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Adrian Medley', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Andrew Phelan', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Matthew Prigmore', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Paul Rubelt', 14, N'Senior' , N'Healthy' , N'Active'),
 (N'Keegan Smith', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'UCF Defense', 14, N' ', N'Healthy', N'Active'),
 (N'Colton Boomer', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Kevin Carrigan', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Grant Reddick', 14, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael Carter', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Mitch McCarthy', 14, N'Junior' , N'Healthy' , N'Active'),
 (N'Jack Bernstein', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Aidan Fedigan', 14, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Gage King', 14, N'Senior' , N'Healthy' , N'Active'); -- 933
GO

-- Utah Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Luke Bottari', 15, N'Senior' , N'Healthy' , N'Active'), --934
 (N'Sam Huard', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Cameron Rising', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Brandon Rose', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Isaac Wilson', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Hunter Andrews', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Micah Bernard', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Laython Biddle', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaylon Glover', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Mike Mitchell', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Omar Shah', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dijon Stanley', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Charlie Vincent', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Anthony Woods', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Damien Alford', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Luca Caldarella', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Matt Clark', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Rayshawn Glover', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Kaimana Hanohano', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Diezel Kamoku', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Taeshaun Lyons', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Munir McClain', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Jett Meine', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Cameron Mitchell', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Money Parks', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Mycah Pittman', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Peyton Rice', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dorian Singer', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'David Washington', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Zacharyus Williams', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Daidren Zipperer', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Dallen Bentley', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Justice Brusatto', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Spencer Clegg', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Frankie Goodson', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'CJ Jacobsen', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Landen King', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Brant Kuithe', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Caleb Lohner', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Carsen Ryan', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Miki Suguturaga', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Roger Alderman', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Spencer Fano', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Isaiah Garcia', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Alex Harrison', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Lukas Jackson', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Falcon Kaumatule', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Jaren Kump', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Caleb Lomu', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Johnny Maea', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Shintaro Mann', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Solatoa Moea''i', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Michael Mokofisi', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Brennan Molina', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Keith Olson', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Reece Parmenter', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kamilo Raass', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Alma Taleni', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tanoa Togiai', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Zereoue Williams', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Utah Defense', 15, N' ', N'Healthy', N'Active'),
 (N'Cole Becker', 15, N'Senior' , N'Healthy' , N'Active'),
 (N'Joey Cheek', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Trey Coleman', 15, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jack Bouwmeester', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Elliot Janish', 15, N'Junior' , N'Healthy' , N'Active'),
 (N'Logan Castor', 15, N'Sophomore' , N'Healthy' , N'Active'),
 (N'JT Greep', 15, N'Senior' , N'Healthy' , N'Active'); -- 1001
GO

-- West Virginia Players
INSERT INTO Football.Player([Name], TeamID, Class, HealthStatus, BenchStatus)
VALUES 
  (N'Ryder Burton', 16, N'Freshman' , N'Healthy' , N'Active'), -- 1002
 (N'Jackson Crist', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Abe Fenwick', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Garrett Greene', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Scott Kean', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Nicco Marchiol', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Khalil Wilkins', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jaylen Anderson', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Clay Ash', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Murphy Clement', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'CJ Donaldson Jr.', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Trae''von Dunbar', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Diore Hubbard', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Judah Price', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Jahiem White', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Colin McBee', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Jaden Bray', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Hudson Clement', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'C.J. Cole', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Dom Collins', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Mykel Davis', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Tyler Evans', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Ric''Darious Farmer', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Preston Fox', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Rodney Gallagher III', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'TJ Johnson', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Andrew Phares', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Traylon Ray', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Brandon Rehmann', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Justin Robinson', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Jarel Williams', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Noah Braham', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Treylan Davis', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Will Dixon', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Greg Genross', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Jack Sammarco', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Kole Taylor', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Kyle Altuner', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Lucas Austin', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Xavier Bausley', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Bryce Biggs', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Aiden Ellis', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Griffin Fogle', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Wesley Hancock', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Ja''Quay Hubbard', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Andreas Hunter', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Nick Krahe', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Landen Livingston', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Nick Malone', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Wyatt Milum', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Tomas Rimac', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Justin Terry', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Sullivan Weidman', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Johnny Williams IV', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Brandon Yates', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Cooper Young', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'West Virginia Defense', 16, N' ', N'Healthy', N'Active'),
 (N'Nate Flower', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Michael Hayes II', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'RJ Kocan', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Casey Stanley', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Leighton Bechdel', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Luke Savino', 16, N'Freshman' , N'Healthy' , N'Active'),
 (N'Oliver Straw', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Ronan Swope', 16, N'Junior' , N'Healthy' , N'Active'),
 (N'Austin Brinkman', 16, N'Senior' , N'Healthy' , N'Active'),
 (N'Macguire Moss', 16, N'Sophomore' , N'Healthy' , N'Active'),
 (N'Kaden Seller', 16, N'Freshman' , N'Healthy' , N'Active'); -- 1069
GO