IF OBJECT_ID(N'Football.FantasyTeamPlayer') IS NULL
BEGIN
	CREATE TABLE Football.FantasyTeamPlayer
	(
		[PlayerID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY
			FOREIGN KEY REFERENCES(),
		[FantasyTeamID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY
			FOREIGN KEY REFERENCES(),
		[PositionID] INT NOT NULL FOREIGN KEY REFERENCES(),
	);
END